WiFiBit.connectToWiFiBit()
WiFiBit.connectToWiFiNetwork("SSID", "key")
WiFiBit.disconnectFromWiFiNetwork()
WiFiBit.disconnectFromWiFiNetwork()
WiFiBit.executeAtCommand("AT", 1000)
WiFiBit.executeHttpMethod(HttpMethod.GET, "google.com", 80, "/search?q=something")
WiFiBit.writeBlynkPinValue("510", "A0", "14dabda3551b4dd5ab46464af582f7d2")
WiFiBit.writeBlynkIoTPinValue("1", "V1", "BzMEzpZ9Bud9ZUXZoJVEkbfneCavDVDx")
WiFiBit.readBlynkIoTPinValue("V1", "BzMEzpZ9Bud9ZUXZoJVEkbfneCavDVDx")
WiFiBit.newline()